---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Cargar las librerias

```{r}

library(tidyverse) #Librerias
library(dplyr)

```

Cargar los datos

```{r}

answers <- read_csv('answers.csv')
question_tags <- read_csv('question_tags.csv')
questions <- read_csv('questions.csv')
tags <- read_csv('tags.csv')

```

1. Left-joining questions and tags

```{r}

#1.1 Relacione questions y question_tags usando las columnas id y question_id, respectivamente.

questions %>%
  left_join(question_tags, by=c("id" = "question_id"))

#1.2 Agregue una relación más para la tabla tags

questions %>%
  left_join(question_tags, by=c("id" = "question_id")) %>%
  left_join(tags, by=c("tag_id" = "id"))

#1.3 Utilice replace_na para cambiar los NA en la columna tag_name a "only-r".

questions %>%
  left_join(question_tags, by=c("id" = "question_id")) %>%
  left_join(tags, by=c("tag_id" = "id")) %>%
  replace_na(list(tag_name="only-r", tag_id=0)) #Reemplazar el n/a

#1.4 Por último, almacene el resultado en la variable questions_with_tags.

questions_with_tags <- questions %>%
  left_join(question_tags, by=c("id" = "question_id")) %>%
  left_join(tags, by=c("tag_id" = "id")) %>%
  replace_na(list(tag_name="only-r", tag_id=0)) #Reemplazar el n/a

```

2. Comparing scores across tags

```{r}

#2.1 Utilice questions_with_tags y aplique group_by para la variable tag_name.

questions_with_tags %>%
  group_by(tag_name)

#2.2 Aplique summarize para obtener el score promedio de cada pregunta y asígnele el nombre mean_score.

questions_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score = mean(score)) 

#2.3 Ordene mean_score en forma descendente.

questions_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score = mean(score)) %>%
  arrange(desc(mean_score))


```

3. Finding gaps between questions and answers

```{r}

questions
answers

#3.1 Utilice inner_join para combinar las tablas questions y answers, luego aplique los sufijos "_question" y "_answer", respectivamente.

questions %>%
  inner_join(answers, by= c("id" = "question_id"), suffix= c("_question", "_answer"))

#3.2 Agregue una nueva columna utilizando la función mutate. La nueva columna se llamará gap y contendrá la resta de creation_date_answer y creation_date_question. (creation_date_answer - creation_date_question).

questions %>%
  inner_join(answers, by= c("id" = "question_id"), suffix= c("_question", "_answer")) %>%
   mutate (gap = creation_date_answer-creation_date_question)

```

4. Joining question and answer counts

```{r}

#4.1 Cuente y ordene la columna question_id en la tabla de answers, luego almacene el resultado en la variable answer_counts.

answer_counts <- answers %>%
  count(question_id) %>%
  arrange(desc(n))

#4.2 Relacione la tabla questions con answer_counts (utilice left_join)

questions %>%
  left_join(answer_counts, by=c("id" = "question_id"))

#4.3 Reemplace los valores NA en la columna n con ceros.

questions %>%
  left_join(answer_counts, by=c("id" = "question_id")) %>%
  replace_na(list(n=0)) #Reemplazar el n/a

#4.4 Por último almacene el resultado en la variable question_answer_counts

question_answer_counts <- questions %>%
  left_join(answer_counts, by=c("id" = "question_id")) %>%
  replace_na(list(n=0)) #Reemplazar el n/a

```


5. Joining questions, answers, and tags

```{r}

#5.1 Combine question_tags con question_answer_counts usando inner_join.

question_tags %>%
  inner_join(question_answer_counts, by=c("question_id" = "id"))

#5.2 Ahora, use otro inner_join para agregar la tabla tags.

question_tags %>%
  inner_join(question_answer_counts, by=c("question_id" = "id")) %>%
  inner_join(tags, by=c("question_id" = "id"))


```








